version: '3.5'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5403:5432"
    networks:
      default:
        aliases:
          - stone-bank-db

  web:
    build:
      context: .
      dockerfile: Dockerfile-mix
    volumes:
      - .:/stone_bank
      - "build:/stone_bank/_build"
      - "deps:/stone_bank/deps"  
    environment:
      - MIX_ENV=prod
      - PG_HOST=stone-bank-db
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: Dockerfile-mix
    command: mix do ecto.drop, ecto.create, ecto.migrate, test, credo --strict
    volumes:
      - .:/stone_bank
      - "build:/stone_bank/_build"
      - "deps:/stone_bank/deps"
    environment:
      - MIX_ENV=test
      - PG_HOST=stone-bank-db
    depends_on:
      - db

  release:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIX_ENV=prod
      - PG_HOST=stone-bank-db
    depends_on:
      - db

volumes:
  build:
  deps:
